Task.create!(name:"go to the grocery store")
Task.create!(name:"brush dog")
Task.create!(name:"kick the cat outside")
Task.create!(name:"clean apartment")
Task.create!(name:"wash dishes")
Task.create!(name:"do some laundry")
Task.create!(name:"drink plenty of water")
Task.create!(name:"embrace the madness")
Task.create!(name:"watch some Voyager")
Task.create!(name:"listen to Pandora")